const fruitValues = [
  { name: "West Dragon", value: 5100000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
  { name: "East Dragon", value: 4650000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
  { name: "Kitsune", value: 600000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6f/KitsuneFruit.png" },
  { name: "Tiger", value: 150000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b5/LeopardFruit.png" },
  { name: "Yeti", value: 140000000, demand: 8, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BlizzardFruit.png" },
  { name: "Control", value: 120000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/9/90/ControlFruit.png" },
  { name: "Lightning", value: 80000000, demand: 8, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
  { name: "Gas", value: 60000000, demand: 8, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/61/SmokeFruit.png" },
  { name: "Dough", value: 30000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/DoughFruit.png" },
  { name: "T-Rex", value: 20000000, demand: 7, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b8/T-RexFruit.png" },
  { name: "Venom", value: 20000000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/c5/VenomFruit.png" },
  { name: "Spirit", value: 10000000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/0/07/SpiritFruit.png" },
  { name: "Mammoth", value: 10000000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/14/MammothFruit.png" },
  { name: "Gravity", value: 10000000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/a2/GravityFruit.png" },
  { name: "Pain", value: 10000000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/f/f0/PainFruit.png" },
  { name: "Portal", value: 10000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/cb/PortalFruit.png" },
  { name: "Buddha", value: 10000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BuddhaFruit.png" },
  { name: "Shadow", value: 6500000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/66/ShadowFruit.png" },
  { name: "Blizzard", value: 5000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BlizzardFruit.png" },
  { name: "Creation", value: 3000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/DoughFruit.png" },
  { name: "Phoenix", value: 2750000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/8/89/PhoenixFruit.png" },
  { name: "Sound", value: 2500000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/30/SoundFruit.png" },
  { name: "Spider", value: 1500000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/SpiderFruit.png" },
  { name: "Love", value: 1500000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/LoveFruit.png" },
  { name: "Quake", value: 1000000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/0/07/QuakeFruit.png" },
  { name: "Magma", value: 1000000, demand: 7, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4d/MagmaFruit.png" },
  { name: "Ghost", value: 800000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ef/GhostFruit.png" },
  { name: "Light", value: 800000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4a/LightFruit.png" },
  { name: "Rubber", value: 600000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1c/RubberFruit.png" },
  { name: "Barrier", value: 500000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/a8/BarrierFruit.png" },
  { name: "Ice", value: 400000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/e4/IceFruit.png" },
  { name: "Dark", value: 350000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4b/DarkFruit.png" },
  { name: "Sand", value: 300000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/8/87/SandFruit.png" },
  { name: "Diamond", value: 250000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6b/DiamondFruit.png" },
  { name: "Falcon", value: 200000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b3/FalconFruit.png" },
  { name: "Flame", value: 200000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ec/FlameFruit.png" },
  { name: "Spike", value: 100000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/68/SpikeFruit.png" },
  { name: "Smoke", value: 80000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/61/SmokeFruit.png" },
  { name: "Bomb", value: 60000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/13/BombFruit.png" },
  { name: "Spring", value: 50000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/e3/SpringFruit.png" },
  { name: "Chop", value: 40000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/7/77/ChopFruit.png" },
  { name: "Spin", value: 30000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/be/SpinFruit.png" },
  { name: "Rocket", value: 10000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/30/RocketFruit.png" }
];

window.fruitValues = fruitValues;
