const tradeItems = {
  "Fruits": [
    { name: "West Dragon", value: 5100000000, demand: 10, image: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" },
    { name: "East Dragon", value: 4650000000, demand: 10, image: "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" },
    { name: "Kitsune", value: 600000000, demand: 10, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/6/65/Kitsune_Fruit.png" },
    { name: "Tiger", value: 150000000, demand: 9, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/a/a3/Leopard_Fruit.png" },
    { name: "Yeti", value: 140000000, demand: 8, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/2/2f/Yeti_Fruit.png/revision/latest" },
    { name: "Control", value: 120000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/1/19/Control_Fruit.png" },
    { name: "Blue Lightning", value: 80000000, demand: 8, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/7/78/Lightning_Fruit.png" },
    { name: "Gas", value: 60000000, demand: 8, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/e/ed/Gas_Fruit.png/revision/latest" },
    { name: "Dough", value: 30000000, demand: 9, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/0/02/Dough_Fruit.png" },
    { name: "T-Rex", value: 20000000, demand: 7, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/d/d9/T-Rex_Fruit.png" },
    { name: "Venom", value: 20000000, demand: 6, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/d/d2/Venom_Fruit.png" },
    { name: "Spirit", value: 10000000, demand: 6, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/6/66/Spirit_Fruit.png" },
    { name: "Mammoth", value: 10000000, demand: 6, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/9/95/Mammoth_Fruit.png" },
    { name: "Gravity", value: 10000000, demand: 2, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/5f/Gravity_Fruit.png" },
    { name: "Pain", value: 10000000, demand: 2, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/4/40/Pain_Fruit.png" },
    { name: "Portal", value: 10000000, demand: 9, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/8a/Portal_Fruit.png" },
    { name: "Buddha", value: 10000000, demand: 10, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/d/df/Buddha_Fruit.png" },
    { name: "Shadow", value: 6500000, demand: 4, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/58/Shadow_Fruit.png" },
    { name: "Blizzard", value: 5000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/c9/Blizzard_Fruit.png" },
    { name: "Creation", value: 3000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/0/02/Dough_Fruit.png" },
    { name: "Phoenix", value: 2750000, demand: 3, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/f/fc/Phoenix_Fruit.png" },
    { name: "Sound", value: 2500000, demand: 4, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/b/ba/Sound_Fruit.png" },
    { name: "Spider", value: 1500000, demand: 3, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/6/61/Spider_Fruit.png" },
    { name: "Love", value: 1500000, demand: 3, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/b/b3/Love_Fruit.png" },
    { name: "Quake", value: 1000000, demand: 3, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/4/42/Quake_Fruit.png" },
    { name: "Magma", value: 1000000, demand: 7, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/2/27/Magma_Fruit.png" },
    { name: "Ghost", value: 800000, demand: 3, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/8c/Ghost_Fruit.png" },
    { name: "Light", value: 800000, demand: 6, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/83/Light_Fruit.png" },
    { name: "Rubber", value: 600000, demand: 2, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/5c/Rubber_Fruit.png" },
    { name: "Ice", value: 400000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/c5/Ice_Fruit.png" },
    { name: "Dark", value: 350000, demand: 4, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/5c/Dark_Fruit.png" },
    { name: "Sand", value: 300000, demand: 2, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/7/72/Sand_Fruit.png" },
    { name: "Diamond", value: 250000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/88/Diamond_Fruit.png" },
    { name: "Flame", value: 200000, demand: 4, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/c4/Flame_Fruit.png" },
    { name: "Spike", value: 100000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/ce/Spike_Fruit.png" },
    { name: "Smoke", value: 80000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/7/7e/Smoke_Fruit.png" },
    { name: "Bomb", value: 60000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/4/43/Bomb_Fruit.png" },
    { name: "Spring", value: 50000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/8a/Spring_Fruit.png" },
    { name: "Chop", value: 40000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/0/0e/Chop_Fruit.png" },
    { name: "Spin", value: 30000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/88/Spin_Fruit.png" },
    { name: "Rocket", value: 10000, demand: 1, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/cb/Rocket_Fruit.png" }
  ],
  "Permanent Fruits": [
    { name: "Perm West Dragon", value: 10590000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/2/29/Dragon_Fruit.png" },
    { name: "Perm East Dragon", value: 10590000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/2/29/Dragon_Fruit.png" },
    { name: "Perm Control", value: 9000000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/1/19/Control_Fruit.png" },
    { name: "Perm Kitsune", value: 9000000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/6/65/Kitsune_Fruit.png" },
    { name: "Perm Yeti", value: 7440000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/2/2f/Yeti_Fruit.png/revision/latest" },
    { name: "Perm Tiger", value: 7440000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/a/a3/Leopard_Fruit.png" },

    { name: "Perm Spirit", value: 5250000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/6/66/Spirit_Fruit.png" },
    { name: "Perm Gas", value: 5250000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/e/ed/Gas_Fruit.png/revision/latest" },
    { name: "Perm Dough", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/0/02/Dough_Fruit.png" },
    { name: "Perm T-Rex", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/d/d9/T-Rex_Fruit.png" },
    { name: "Perm Mammoth", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/9/95/Mammoth_Fruit.png" },
    { name: "Perm Venom", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/d/d2/Venom_Fruit.png" },
    { name: "Perm Shadow", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/58/Shadow_Fruit.png" },
    { name: "Perm Gravity", value: 4230000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/5f/Gravity_Fruit.png" },
    { name: "Perm Pain", value: 3720000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/4/40/Pain_Fruit.png" },
    { name: "Perm Blue Lightning", value: 3540000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/7/78/Lightning_Fruit.png" },
    { name: "Perm Portal", value: 3420000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/8a/Portal_Fruit.png" },
    { name: "Perm Buddha", value: 2970000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/d/df/Buddha_Fruit.png" },
    { name: "Perm Blizzard", value: 2790000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/c9/Blizzard_Fruit.png" },
    { name: "Perm Phoenix", value: 2400000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/f/fc/Phoenix_Fruit.png" },
    { name: "Perm Creation", value: 2040000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/0/02/Dough_Fruit.png" },
    { name: "Perm Ghost", value: 1890000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/8c/Ghost_Fruit.png" },
    { name: "Perm Rubber", value: 1740000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/5c/Rubber_Fruit.png" },
    { name: "Perm Magma", value: 1650000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/2/27/Magma_Fruit.png" },
    { name: "Perm Light", value: 1500000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/83/Light_Fruit.png" },
    { name: "Perm Spider", value: 1500000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/6/61/Spider_Fruit.png" },
    { name: "Perm Sound", value: 1350000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/b/ba/Sound_Fruit.png" },
    { name: "Perm Dark", value: 1260000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/5/5c/Dark_Fruit.png" },
    { name: "Perm Quake", value: 1200000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/4/42/Quake_Fruit.png" },
    { name: "Perm Sand", value: 1080000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/7/72/Sand_Fruit.png" },
    { name: "Perm Love", value: 1020000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/b/b3/Love_Fruit.png" },
    { name: "Perm Ice", value: 900000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/c5/Ice_Fruit.png" },
    { name: "Perm Diamond", value: 750000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/88/Diamond_Fruit.png" },
    { name: "Perm Flame", value: 450000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/c4/Flame_Fruit.png" },
    { name: "Perm Spike", value: 140000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/ce/Spike_Fruit.png" },
    { name: "Perm Smoke", value: 120000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/7/7e/Smoke_Fruit.png" },
    { name: "Perm Bomb", value: 90000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/4/43/Bomb_Fruit.png" },
    { name: "Perm Spring", value: 60000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/8a/Spring_Fruit.png" },
    { name: "Perm Blade", value: 20000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/0/0e/Chop_Fruit.png" },
    { name: "Perm Spin", value: 15000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/8/88/Spin_Fruit.png" },
    { name: "Perm Rocket", value: 10000000, demand: 5, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/cb/Rocket_Fruit.png" }
  ],
  "Gamepasses": [
    { name: "Fruit Notifier", value: 6900000000, demand: 10, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/9/98/BadgeFruitNotifier.png" },
    { name: "Dark Blade", value: 1740000000, demand: 9, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/a/a0/Dark_Blade.png" },
    { name: "+1 Fruit Storage", value: 450000000, demand: 10, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/6/6a/BadgeFruitStorage.png" },
    { name: "2x Mastery", value: 450000000, demand: 9, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/1/16/BadgeMasteryx2.png" },
    { name: "2x Money", value: 450000000, demand: 9, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/c/cf/BadgeMoneyx2.png" },
    { name: "2x Boss Drops", value: 300000000, demand: 7, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/3/3a/BadgeBossDrops.png" },
    { name: "Fast Boats", value: 300000000, demand: 7, image: "https://static.wikia.nocookie.net/roblox-blox-piece/images/7/77/FastBoats.png" }
  ],
  "Skins": [
    { name: "Permanent Dragon Token", value: 0, demand: 5, image: "" },
    { name: "Fiend Yeti", value: 870000000, demand: 5, image: "" },
    { name: "Galaxy Empyrean Kitsune", value: 15000000000, demand: 5, image: "" },
    { name: "Crimson Kitsune", value: 11700000000, demand: 5, image: "" },
    { name: "Ember West Dragon", value: 8250000000, demand: 5, image: "" },
    { name: "Purple Lightning", value: 6900000000, demand: 5, image: "" },
    { name: "Meme-Meme", value: 6840000000, demand: 5, image: "" },
    { name: "Yellow Lightning", value: 2100000000, demand: 5, image: "" },
    { name: "Red Lightning", value: 2040000000, demand: 5, image: "" },
    { name: "Super Spirit Pain", value: 2010000000, demand: 5, image: "" },
    { name: "Divine Portal", value: 1710000000, demand: 5, image: "" },
    { name: "Werewolf", value: 1050000000, demand: 5, image: "" },
    { name: "Sadness Pain", value: 570000000, demand: 5, image: "" },
    { name: "Celestial Pain", value: 570000000, demand: 5, image: "" },
    { name: "Green Lightning", value: 570000000, demand: 5, image: "" },
    { name: "Azura Bomb", value: 420000000, demand: 5, image: "" },
    { name: "Thermite Bomb", value: 420000000, demand: 5, image: "" },
    { name: "Nuclear Bomb", value: 420000000, demand: 5, image: "" },
    { name: "Frustration Pain", value: 330000000, demand: 5, image: "" },
    { name: "Eagle Matrix", value: 210000000, demand: 5, image: "" },
    { name: "Rose Quartz Diamond", value: 180000000, demand: 5, image: "" },
    { name: "Emerald Diamond", value: 150000000, demand: 5, image: "" },
    { name: "Topaz Diamond", value: 150000000, demand: 5, image: "" },
    { name: "Eagle Requiem", value: 140000000, demand: 5, image: "" },
    { name: "Eclipse", value: 120000000, demand: 5, image: "" },
    { name: "Ruby Diamond", value: 90000000, demand: 5, image: "" },
    { name: "Torment Pain", value: 80000000, demand: 5, image: "" },
    { name: "Dragon Token", value: 60000000, demand: 5, image: "" },
    { name: "Eagle Glacier", value: 20000000, demand: 5, image: "" },
    { name: "Celebration Bomb", value: 10000000, demand: 5, image: "" },
    { name: "Parrot", value: 4600000000, demand: 5, image: "" },
    { name: "Orange Portal", value: 0, demand: 5, image: "" }
  ]
};

window.tradeItems = tradeItems;
