const tradeItems = {
  "Fruits": [
    { name: "West Dragon", value: 5100000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
    { name: "East Dragon", value: 4650000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
    { name: "Kitsune", value: 600000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6f/KitsuneFruit.png" },
    { name: "Tiger", value: 150000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b5/LeopardFruit.png" },
    { name: "Yeti", value: 140000000, demand: 8, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BlizzardFruit.png" },
    { name: "Control", value: 120000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/9/90/ControlFruit.png" },
    { name: "Lightning", value: 80000000, demand: 8, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
    { name: "Gas", value: 60000000, demand: 8, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/61/SmokeFruit.png" },
    { name: "Dough", value: 30000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/DoughFruit.png" },
    { name: "T-Rex", value: 20000000, demand: 7, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b8/T-RexFruit.png" },
    { name: "Venom", value: 20000000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/c5/VenomFruit.png" },
    { name: "Spirit", value: 10000000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/0/07/SpiritFruit.png" },
    { name: "Mammoth", value: 10000000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/14/MammothFruit.png" },
    { name: "Gravity", value: 10000000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/a2/GravityFruit.png" },
    { name: "Pain", value: 10000000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/f/f0/PainFruit.png" },
    { name: "Portal", value: 10000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/cb/PortalFruit.png" },
    { name: "Buddha", value: 10000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BuddhaFruit.png" },
    { name: "Shadow", value: 6500000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/66/ShadowFruit.png" },
    { name: "Blizzard", value: 5000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BlizzardFruit.png" },
    { name: "Creation", value: 3000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/DoughFruit.png" },
    { name: "Phoenix", value: 2750000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/8/89/PhoenixFruit.png" },
    { name: "Sound", value: 2500000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/30/SoundFruit.png" },
    { name: "Spider", value: 1500000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/SpiderFruit.png" },
    { name: "Love", value: 1500000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/LoveFruit.png" },
    { name: "Quake", value: 1000000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/0/07/QuakeFruit.png" },
    { name: "Magma", value: 1000000, demand: 7, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4d/MagmaFruit.png" },
    { name: "Ghost", value: 800000, demand: 3, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ef/GhostFruit.png" },
    { name: "Light", value: 800000, demand: 6, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4a/LightFruit.png" },
    { name: "Rubber", value: 600000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1c/RubberFruit.png" },
    { name: "Barrier", value: 500000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/a8/BarrierFruit.png" },
    { name: "Ice", value: 400000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/e4/IceFruit.png" },
    { name: "Dark", value: 350000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4b/DarkFruit.png" },
    { name: "Sand", value: 300000, demand: 2, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/8/87/SandFruit.png" },
    { name: "Diamond", value: 250000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6b/DiamondFruit.png" },
    { name: "Falcon", value: 200000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b3/FalconFruit.png" },
    { name: "Flame", value: 200000, demand: 4, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ec/FlameFruit.png" },
    { name: "Spike", value: 100000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/68/SpikeFruit.png" },
    { name: "Smoke", value: 80000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/61/SmokeFruit.png" },
    { name: "Bomb", value: 60000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/13/BombFruit.png" },
    { name: "Spring", value: 50000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/e3/SpringFruit.png" },
    { name: "Chop", value: 40000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/7/77/ChopFruit.png" },
    { name: "Spin", value: 30000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/be/SpinFruit.png" },
    { name: "Rocket", value: 10000, demand: 1, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/30/RocketFruit.png" }
  ],
  "Permanent Fruits": [
    { name: "Perm West Dragon", value: 10590000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
    { name: "Perm East Dragon", value: 10590000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
    { name: "Perm Control", value: 9000000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/9/90/ControlFruit.png" },
    { name: "Perm Kitsune", value: 9000000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6f/KitsuneFruit.png" },
    { name: "Perm Yeti", value: 7440000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BlizzardFruit.png" },
    { name: "Perm Tiger", value: 7440000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b5/LeopardFruit.png" },

    { name: "Perm Spirit", value: 5250000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/0/07/SpiritFruit.png" },
    { name: "Perm Gas", value: 5250000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/61/SmokeFruit.png" },
    { name: "Perm Dough", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/DoughFruit.png" },
    { name: "Perm T-Rex", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b8/T-RexFruit.png" },
    { name: "Perm Mammoth", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/14/MammothFruit.png" },
    { name: "Perm Venom", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/c5/VenomFruit.png" },
    { name: "Perm Shadow", value: 4800000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/66/ShadowFruit.png" },
    { name: "Perm Gravity", value: 4230000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/a2/GravityFruit.png" },
    { name: "Perm Pain", value: 3720000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/f/f0/PainFruit.png" },
    { name: "Perm Lightning", value: 3540000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
    { name: "Perm Portal", value: 3420000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/cb/PortalFruit.png" },
    { name: "Perm Buddha", value: 2970000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BuddhaFruit.png" },
    { name: "Perm Blizzard", value: 2790000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BlizzardFruit.png" },
    { name: "Perm Phoenix", value: 2400000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/8/89/PhoenixFruit.png" },
    { name: "Perm Creation", value: 2040000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/DoughFruit.png" },
    { name: "Perm Ghost", value: 1890000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ef/GhostFruit.png" },
    { name: "Perm Rubber", value: 1740000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1c/RubberFruit.png" },
    { name: "Perm Magma", value: 1650000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4d/MagmaFruit.png" },
    { name: "Perm Light", value: 1500000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4a/LightFruit.png" },
    { name: "Perm Spider", value: 1500000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/SpiderFruit.png" },
    { name: "Perm Sound", value: 1350000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/30/SoundFruit.png" },
    { name: "Perm Eagle", value: 1310000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b3/FalconFruit.png" },
    { name: "Perm Dark", value: 1260000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4b/DarkFruit.png" },
    { name: "Perm Quake", value: 1200000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/0/07/QuakeFruit.png" },
    { name: "Perm Sand", value: 1080000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/8/87/SandFruit.png" },
    { name: "Perm Love", value: 1020000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/1a/LoveFruit.png" },
    { name: "Perm Ice", value: 900000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/e4/IceFruit.png" },
    { name: "Perm Diamond", value: 750000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6b/DiamondFruit.png" },
    { name: "Perm Barrier", value: 600000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/a8/BarrierFruit.png" },
    { name: "Perm Flame", value: 450000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ec/FlameFruit.png" },
    { name: "Perm Spike", value: 140000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/68/SpikeFruit.png" },
    { name: "Perm Smoke", value: 120000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/61/SmokeFruit.png" },
    { name: "Perm Bomb", value: 90000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/13/BombFruit.png" },
    { name: "Perm Spring", value: 60000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/e3/SpringFruit.png" },
    { name: "Perm Blade", value: 20000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/7/77/ChopFruit.png" },
    { name: "Perm Spin", value: 15000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/be/SpinFruit.png" },
    { name: "Perm Rocket", value: 10000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/30/RocketFruit.png" }
  ],
  "Gamepasses": [
    { name: "Fruit Notifier", value: 6900000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/68/Fruit_Notifier.png" },
    { name: "Dark Blade", value: 1740000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/5/5e/Dark_Blade_Gamepass.png" },
    { name: "+1 Fruit Storage", value: 450000000, demand: 10, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/30/Fruit_Storage.png" },
    { name: "2x Mastery", value: 450000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/7/74/2x_Mastery.png" },
    { name: "2x Money", value: 450000000, demand: 9, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/3/3c/2x_Money.png" },
    { name: "2x Boss Drops", value: 300000000, demand: 7, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/2/23/Boss_Drops.png" },
    { name: "Fast Boats", value: 300000000, demand: 7, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/8/82/Fast_Boats.png" }
  ],
  "Skins": [
    { name: "Permanent Dragon Token", value: 0, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
    { name: "Fiend Yeti", value: 870000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BlizzardFruit.png" },
    { name: "Galaxy Empyrean Kitsune", value: 15000000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6f/KitsuneFruit.png" },
    { name: "Crimson Kitsune", value: 11700000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6f/KitsuneFruit.png" },
    { name: "Ember West Dragon", value: 8250000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
    { name: "Purple Lightning", value: 6900000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
    { name: "Meme-Meme", value: 6840000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/e/ea/BuddhaFruit.png" },
    { name: "Blue Lightning", value: 3540000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
    { name: "Yellow Lightning", value: 2100000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
    { name: "Red Lightning", value: 2040000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
    { name: "Super Spirit Pain", value: 2010000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/0/07/SpiritFruit.png" },
    { name: "Divine Portal", value: 1710000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/cb/PortalFruit.png" },
    { name: "Werewolf", value: 1050000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b5/LeopardFruit.png" },
    { name: "Sadness Pain", value: 570000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/f/f0/PainFruit.png" },
    { name: "Celestial Pain", value: 570000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/f/f0/PainFruit.png" },
    { name: "Green Lightning", value: 570000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/a/ab/RumbleFruit.png" },
    { name: "Azura Bomb", value: 420000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/13/BombFruit.png" },
    { name: "Thermite Bomb", value: 420000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/13/BombFruit.png" },
    { name: "Nuclear Bomb", value: 420000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/13/BombFruit.png" },
    { name: "Frustration Pain", value: 330000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/f/f0/PainFruit.png" },
    { name: "Eagle Matrix", value: 210000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b3/FalconFruit.png" },
    { name: "Rose Quartz Diamond", value: 180000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6b/DiamondFruit.png" },
    { name: "Emerald Diamond", value: 150000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6b/DiamondFruit.png" },
    { name: "Topaz Diamond", value: 150000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6b/DiamondFruit.png" },
    { name: "Eagle Requiem", value: 140000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b3/FalconFruit.png" },
    { name: "Eclipse", value: 120000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/4/4b/DarkFruit.png" },
    { name: "Ruby Diamond", value: 90000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/6/6b/DiamondFruit.png" },
    { name: "Torment Pain", value: 80000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/f/f0/PainFruit.png" },
    { name: "Dragon Token", value: 60000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/18/DragonFruit.png" },
    { name: "Eagle Glacier", value: 20000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b3/FalconFruit.png" },
    { name: "Celebration Bomb", value: 10000000, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/1/13/BombFruit.png" },
    { name: "Parrot", value: 0, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/b/b3/FalconFruit.png" },
    { name: "Orange Portal", value: 0, demand: 5, image: "https://static.wikia.nocookie.net/blox-fruits-wiki/images/c/cb/PortalFruit.png" }
  ]
};

window.tradeItems = tradeItems;
